### PR TITLE
dep: update to latest master of TM

### PR DESCRIPTION
**Pull request by marbar3778**

### CODE REVIEW

**Comment by erikgrinaker** [comment]
This doesn't seem right to me: why are these APIs now taking Protobuf messages?

**Comment by marbar3778** [comment]
ProofOp/Proof was always a proto type, but now the location of the file has moved.

**Comment by erikgrinaker** [comment]
Ok, that seems like a bit of a code smell to me, but sure. If we merge this we can't cut 0.15 until Tendermint 0.34 is out; we cool with that?

**Comment by marbar3778** [comment]
that's how it has always been with this repo. The only way to avoid this is to remove tm dep on proofs but this has other consequences.

**Pull request merged**
