### PR TITLE
solution2: optimize pruning

### PR DESCRIPTION
**Pull request by summerpro**
issue #415

### CODE REVIEW

**Comment by robert-zaremba** [comment]
Does this solution supersedes #416?

**Comment by summerpro** [comment]
> Does this solution supersedes #416?

yes, I closed #416

**Comment by marbar3778** [comment]
@robert-zaremba with how long set is taking and will take, it might make sense to add this?

**Comment by robert-zaremba** [comment]
@marbar3778 , not sure I understand your question... this PR is not ready yet.

**Comment by marbar3778** [comment]
closing this as we revisit everything in this repo

**Pull request closed without merging**
