### PR TITLE
chore: cleanup unnecessary `ndb.Commit` calls

### PR DESCRIPTION
**Pull request by cool-develope**
## Context

There are some unnecessary `ndb.Commit` and `resetBatch` calls which introduced to avoid the large batch commit originally. They are not necessary since we are using `BatchWithFlusher` now.

### CODE REVIEW

**Review by ValarDragon — APPROVED** [review]
Awesome! Just need to get cosmos-db sorted out for batch with flusher on osmosis

**Review by tac0turtle — APPROVED** [review]

**Comment by tac0turtle** [comment]
backport?

**Comment by cool-develope** [comment]
> backport?

not sure, @czarcas7ic osmosis implemented the db wrapper with flusher fully?
I think we can merge it, and later backport when need

**Comment by czarcas7ic** [comment]
@cool-develope I don't think we have batchWithFlusher implemented

**Comment by czarcas7ic** [comment]
Thanks for implementing this for our sdk fork @cool-develope! Seems we are unblocked to merge so we can test

**Comment by czarcas7ic** [comment]
Sorry maybe I am not fully understanding how implementing with flusher has to do with this PR?

In the PR you made @cool-develope, it seems like NewBatch and NewBatchWithSize still behave the same, which I thought that was what needed to be addressed https://github.com/osmosis-labs/cosmos-sdk/blob/6c1422877673277448bc14e2be415133cc6738e6/store/wrapper/tmdb.go#L52-L57

My apologies if my understanding is off here.

**Comment by cool-develope** [comment]
> Sorry maybe I am not fully understanding how implementing with flusher has to do with this PR?
> 
> In the PR you made @cool-develope, it seems like NewBatch and NewBatchWithSize still behave the same, which I thought that was what needed to be addressed https://github.com/osmosis-labs/cosmos-sdk/blob/6c1422877673277448bc14e2be415133cc6738e6/store/wrapper/tmdb.go#L52-L57
> 
> My apologies if my understanding is off here.

`NewBatchSize` is aimed to allocate the memory when create the batch, it will allow to avoid memory grow in batch insertion. It is not directly related to the flusher. The purpose of flusher is to avoid the large batch writing, it writes periodically if the batch size is greater than the threshold. 
Ofc, `NewBatchSize` will increase the performance, unfortunately I have no idea of how to refactor the prefixdb of comet-db. However, we can merge it without `NewBatchSize` still.

**Comment by czarcas7ic** [comment]
Thanks for the explanation!

**Comment by cool-develope** [comment]
@Mergifyio backport release/v1.1.x

**Pull request merged**
