### PR TITLE
optim: remove the buffer when compute node hash

### PR DESCRIPTION
**Pull request by yihuang**
- remove the buffer when compute node hash
- benchmark different ways to hash node

```
$ go test -run=^$ -bench=BenchmarkNode_HashNode -benchmem ./ -count=5
goos: darwin
goarch: amd64
pkg: github.com/cosmos/iavl
cpu: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
BenchmarkNode_HashNode/NoBuffer-12         	 1571757	       757.0 ns/op	     160 B/op	       2 allocs/op
BenchmarkNode_HashNode/NoBuffer-12         	 1594012	       751.8 ns/op	     160 B/op	       2 allocs/op
BenchmarkNode_HashNode/NoBuffer-12         	 1598257	       757.4 ns/op	     160 B/op	       2 allocs/op
BenchmarkNode_HashNode/NoBuffer-12         	 1578457	       745.4 ns/op	     160 B/op	       2 allocs/op
BenchmarkNode_HashNode/NoBuffer-12         	 1613202	       783.7 ns/op	     160 B/op	       2 allocs/op
BenchmarkNode_HashNode/PreAllocate-12      	 1000000	      1129 ns/op	     160 B/op	       3 allocs/op
BenchmarkNode_HashNode/PreAllocate-12      	 1000000	      1098 ns/op	     160 B/op	       3 allocs/op
BenchmarkNode_HashNode/PreAllocate-12      	  974152	      1088 ns/op	     160 B/op	       3 allocs/op
BenchmarkNode_HashNode/PreAllocate-12      	 1000000	      1083 ns/op	     160 B/op	       3 allocs/op
BenchmarkNode_HashNode/PreAllocate-12      	 1000000	      1084 ns/op	     160 B/op	       3 allocs/op
BenchmarkNode_HashNode/NoPreAllocate-12    	 1000000	      1095 ns/op	     144 B/op	       3 allocs/op
BenchmarkNode_HashNode/NoPreAllocate-12    	 1000000	      1068 ns/op	     144 B/op	       3 allocs/op
BenchmarkNode_HashNode/NoPreAllocate-12    	 1000000	      1068 ns/op	     144 B/op	       3 allocs/op
BenchmarkNode_HashNode/NoPreAllocate-12    	 1000000	      1063 ns/op	     144 B/op	       3 allocs/op
BenchmarkNode_HashNode/NoPreAllocate-12    	 1000000	      1060 ns/op	     144 B/op	       3 allocs/op
PASS
ok  	github.com/cosmos/iavl	22.453s
```

### CODE REVIEW

**Comment by tac0turtle** [comment]
is there a comparison to main?

**Comment by tac0turtle** [comment]
oh nvm, I read the benchmark wrong, thanks for the pr

**Review by tac0turtle — APPROVED** [review]

**Comment by tac0turtle** [comment]
cc @elias-orijtech

**Comment by elias-orijtech** [comment]
LGTM.

**Pull request merged**
