### PR TITLE
fix: empty root loading failed

### LINKED ISSUE #711: empty root loading is failed in `GetImmutable`

### PR DESCRIPTION
**Pull request by cool-develope**
Closes #711

### CODE REVIEW

**Review by tac0turtle — COMMENTED** [review]
was this suppose to stay in and got removed earlier on?

**Comment by cool-develope** [comment]
> was this suppose to stay in and got removed earlier on?

no, I think it is related to the recent updates, we refactored the root from the hash (previous) to `NodeKey`, so now nil condition is not working

**Review by tac0turtle — APPROVED** [review]
we should make sure 0.20 is not effected

**Comment by cool-develope** [comment]
> we should make sure 0.20 is not effected

I am sure 0.20 have no related issues, btw are you able to backport it to v1.0.0?

**Comment by tac0turtle** [comment]
@mergifyio backport release/v1.x

**Comment by tac0turtle** [comment]
@Mergifyio backport release/v1.x.x

**Pull request merged**
