### PR TITLE
linting fixes

### PR DESCRIPTION
**Pull request by faddat**
This fixes linting issues exposed by running the linter in #535

### CODE REVIEW

**Review by robert-zaremba — COMMENTED** [review]
shall we limit whitespace changes?

**Comment by faddat** [comment]
maybe not?

so, this was accomplished automatically:

gofumpt -w -l .
golangci-lint run ./...

**Comment by robert-zaremba** [comment]
Fair enough - this was done automatically then. Thanks for the comment @faddat . Probably we should add `gofumpt` to the required linters?

**Review by robert-zaremba — APPROVED** [review]

**Comment by faddat** [comment]
I think there were a few that I didn't do automatically, but the bulk of it, yes

**Review by marbar3778 — APPROVED** [review]

**Comment by faddat** [comment]
Note: this has a 100% chance of passing CI before we merge #535

**Review by marbar3778 — APPROVED** [review]

**Pull request merged**
