### PR TITLE
github: increase test timeout to 10 minutes 

### PR DESCRIPTION
**Pull request by erikgrinaker**
See failure in #333.

### CODE REVIEW

**Review by marbar3778 — APPROVED** [review]
LGTM. 

I saw the error was a data race is this caused by the timeout?

**Comment by erikgrinaker** [comment]
Looks like it. There's one backtrace to the coverage thing, and one hidden one (possibly some internal Go thing). I'm guessing something went wrong while handling the timeout panic.

**Comment by marbar3778** [comment]
It is super odd that this test is running for so long though, is this due to a new change?

**Comment by erikgrinaker** [comment]
`TestRandomOperations` sets up a bunch of trees and runs random operations against them. When the race detector is enabled, this takes forever.

I'm looking into running them in parallel now, although it may make it harder to read the output since the different tests' output will be jumbled together.

**Comment by erikgrinaker** [comment]
Seems to work well enough, #338. Suggest we just do that instead, and drop this timeout bump.

**Comment by erikgrinaker** [comment]
Superseded by #338.

**Pull request closed without merging**
