### PR TITLE
feat: Uses BatchWithFlusher in iavl tree

### PR DESCRIPTION
**Pull request by catShaark**
This PR replace the use of normal dbm.Batch with BatchWithFlusher in iavl tree
It also hard code the value of flushthreshold to 100KB

### CODE REVIEW

**Review by tac0turtle — APPROVED** [review]
LGTM thank you

**Review by cool-develope — APPROVED** [review]
overall looks good to me, except why hard code the flushThreshold?

**Comment by catShaark** [comment]
That's because I discussed with marko and we decide to hard code the value to be the best option showed by benchmark result run on osmosis node

**Comment by julienrbrt** [comment]
+1 on @cool-develope comment.

Given that `newNodeDB` takes `Options` we could add an option in here: https://github.com/notional-labs/iavl/blob/a945f5f903800a214d30e55f87ca96cc6bc78051/options.go#L71-L89 and use `100000` in the DefaultOptions. If going this way, we should make them variadic so you don't end up overwriting that value to 0 by defining new options.

**Comment by tac0turtle** [comment]
@julienrbrt you fine with merging this and then i can make the changes.

**Comment by julienrbrt** [comment]
> @julienrbrt you fine with merging this and then i can make the changes.

Works! We need changelogs as well to reflect some API breaks from here in the follow-up

**Comment by julienrbrt** [comment]
@mergifyio backport release/1.x.x

**Comment by julienrbrt** [comment]
@Mergifyio backport release/v1.x.x

**Comment by tac0turtle** [comment]
@mergifyio backport release/v1.x.x

**Pull request merged**
