### PR TITLE
feat: Change the v0.20.x line to use cosmos DB

### PR DESCRIPTION
**Pull request by ValarDragon**
This is done so we can merge #765

### CODE REVIEW

**Comment by ValarDragon** [comment]
This CI lint seems wrong? I tried changing both of the nolint's in the codebase, but they do warn for a gocritic problem. (Also these are unchanged by this PR)

**Comment by ValarDragon** [comment]
cc @tac0turtle or anyone who worked on the initial cosmos DB move, any idea why benchmarks is getting build errors for rocksDB and how to fix it?

(Also is this something thats acceptable to merge into v0.20.x line?)

**Comment by tac0turtle** [comment]
I can look into this. We have different versions for things due to the comet migration so it's confusing.

**Comment by julienrbrt** [comment]
> I can look into this. We have different versions for things due to the comet migration so it's confusing.

I was looking as well lol -> https://github.com/cosmos/iavl/pull/769
I think we cannot because this will break v0.47.x users.

**Comment by ValarDragon** [comment]
oh yikes thats super confusing. OK :/

Guess I have to revive the IAVL fork until Osmosis updates its SDK

**Comment by tac0turtle** [comment]
@ValarDragon which version of the sdk do you need this for?

**Comment by ValarDragon** [comment]
Its for SDK v0.45! But I think it shouldn't be a big deal to make a more complicated IAVL change here to track the batch size in IAVL instead of the DB layer for this release line.

**Pull request closed without merging**
