### PR TITLE
fix: `traverseNodes` unexpected behaviour

### PR DESCRIPTION
**Pull request by catShaark**
- If there's no update in the latest version of the tree, we [set the root node's value to be the previous root node's key](https://github.com/cosmos/iavl/blob/842d58b63d0cfd82c67987b4bcaac3a9edffecc3/nodedb.go#L545) instead of its marshalled bytes. When we call `traverseNodes`, we iterate through every nodes (including root nodes) and unmarshal the marshalled node's value via `MakeNode`. `MakeNode` is made only for unmarshaling a marshalled node's value, so if a marshalled node's value is actually a node's key like described above, it'll handle incorrectly.
- Suggest that in `traverseNodes` we check if the marshalled node's value is indeed a root node's key so that we can ignore it

### CODE REVIEW

**Comment by cool-develope** [comment]
@catShaark , thanks for catching it, it seems like we need to refactor the `traverseNode` function using `prefixIterate`
FYI, it is a test utility function (not critical part).

**Comment by catShaark** [comment]
should I close this now

**Comment by cool-develope** [comment]
> should I close this now

or you can modify it

**Comment by catShaark** [comment]
ohh, I'll modify this

**Review by cool-develope — APPROVED** [review]

**Comment by tac0turtle** [comment]
@catShaark can we get a changelog here then we can merge

**Comment by catShaark** [comment]
Yess

**Comment by catShaark** [comment]
@tac0turtle, changelog added

**Review by tac0turtle — APPROVED** [review]

**Pull request merged**
