### PR TITLE
feat: deferred pruning

### PR DESCRIPTION
**Pull request by cool-develope**
Closes: #885 

Added the `AsyncPruning` option, it needs to call `SetCommitting` and `UnsetCommitting` when committing in the store module in the async pruning mode.
It doesn't break the original APIs.

### CODE REVIEW

**Comment by czarcas7ic** [comment]
I plan on testing this either this weekend, or this coming week. Thanks so much for making this!

**Review by czarcas7ic — APPROVED** [review]
Worked with @cool-develope and tested against Osmosis mainnet, no issues thus far!

**Comment by tac0turtle** [comment]
before we tag id like to test on dydx. Ill aim to do it this week, but we can go ahead with the merge with one more approval

**Review by sontrinh16 — APPROVED** [review]

**Comment by tac0turtle** [comment]
does this need to be backported?

**Pull request merged**
