### PR TITLE
feat: remove legacy orphans background

### PR DESCRIPTION
**Pull request by cool-develope**
Closes: #862 

## Context

- refactor removing the legacy orphans in background.
- add the mutex in `BatchWithFlusher` to avoid the race condition

### CODE REVIEW

**Comment by ValarDragon** [comment]
Is this concurrency safe with main thread commits? (This can add to deleting while the main thread is committing right?)

**Comment by cool-develope** [comment]
> Is this concurrency safe with main thread commits? (This can add to deleting while the main thread is committing right?)
> 
> Do we need a mutex to ensure the two don't try to add to batch at the same time?

yeah, the test is failed with data racing

**Comment by ValarDragon** [comment]
This is the wrong spot to put it, we hacked something that worked in this branch https://github.com/cosmos/iavl/tree/dev/v1.0.0-orphan

(the first part of the loop is what was expensive)

I think the way you were doing the code is cleaner, just that was something that I got to work. Plz feel free to takeover/move anything that helps :pray:

**Comment by cool-develope** [comment]
close in favor of #877

**Pull request closed without merging**
