### PR TITLE
fix: Add Extra Check for Reformatted Root Node in GetNode

### PR DESCRIPTION
**Pull request by cool-develope**
## Problem Description

When the root node is reformatted due to pruning, its nodeKey changes from (version, 1) to (version, 0). As a result:

	1.	This version becomes invisible during a root search.
	2.	If a node in the next version references the reformatted node, it becomes inaccessible.

## Proposed Solution

Add an extra check in the GetNode function to handle reformatted root nodes. This ensures that:

	•	Reformatted nodes with nodeKey (version, 0) remain accessible.
	•	References to these nodes from subsequent versions are correctly resolved.

## Summary by CodeRabbit

- **New Features**
	- Introduced a new test to validate the behavior of the `MutableTree` after version deletions.
	- Added new APIs: `DeleteVersionsFrom(int64)` and `GetLatestVersion`.

- **Bug Fixes**
	- Enhanced the `GetNode` method to improve retrieval logic for nodes, ensuring better handling of cases with `nil` buffers and legacy nodes.

- **Documentation**
	- Updated the changelog to reflect recent improvements and fixes, including a new section for bug fixes and detailed descriptions of changes.

### CODE REVIEW

**Review by yihuang — APPROVED** [review]

**Comment by yihuang** [comment]
do you need to add a changelog?

**Comment by yihuang** [comment]
shall we merge?

**Review by sontrinh16 — APPROVED** [review]

**Review by tac0turtle — APPROVED** [review]

**Comment by tac0turtle** [comment]
@merfifyio backport release/v1.2.x

**Comment by tac0turtle** [comment]
@mergifyio backport release/v1.3.x

**Pull request merged**
